### ISSUE TITLE
The information doesn't work

### ISSUE THREAD

**Issue by lukasz-stepien-dev** [The-Scripts/Quiz-about-network#15]
**Describe the bug**
When we turn on the Sass compiler in VS Code, the information bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/93351383/201517660-1404bb1a-cc5b-47f3-b09c-1841030f5b95.png)
![image](https://user-images.githubusercontent.com/93351383/201517675-2b57ca90-1cb7-482d-ad29-db96ad9f7f00.png)

**Comment by Patryk-Ruzicki** [comment]
Fixed code in sass
