### ISSUE TITLE
Too large font size on mobile

### ISSUE THREAD

**Issue by KrifiZ** [The-Scripts/Quiz-about-network#8]
### Describe the bug
The value "Previous" from input doesn't  fit the button
### Case
Resolution 320x868, 375x868, 425x868
### Screenshots
![1](https://user-images.githubusercontent.com/52302531/200435619-e62b50f9-51b5-4ad2-b33f-31d0818fdb7c.png)
![2](https://user-images.githubusercontent.com/52302531/200435622-165fb552-5614-4cc9-8fa7-2b8ce7f7e8fa.png)
![3](https://user-images.githubusercontent.com/52302531/200435621-9fa1d71c-1581-41d5-aefd-b93e4f1b997b.png)

**Comment by Patryk-Ruzicki** [comment]
This problem is in the proces of repair

**Comment by kmarcinkowskij** [comment]
Fixed! Thanks for spotting it.
